<?php 
 return array (
  'contact_info_text' => 'Call Us: <a href="tel:1234567890">1-2345-678-90</a>',
  'social_icons_title_1' => 'Facebook',
  'social_icons_link_1' => '#',
  'social_icons_image_1' => get_template_directory_uri().'/assets/images-demo/facebook.svg',
  'social_icons_title_2' => 'Twitter',
  'social_icons_link_2' => '#',
  'social_icons_image_2' =>  get_template_directory_uri().'/assets/images-demo/twitter.svg',
  'social_icons_title_3' => 'IG',
  'social_icons_link_3' => '#',
  'social_icons_image_3' =>  get_template_directory_uri().'/assets/images-demo/instagram.svg',
  'social_icons_title_4' => 'Pinset',
  'social_icons_link_4' => '#',
  'social_icons_image_4' =>  get_template_directory_uri().'/assets/images-demo/pinterest.svg',
  'social_icons_title_5' => 'In',
  'social_icons_link_5' => '#',
  'social_icons_image_5' =>  get_template_directory_uri().'/assets/images-demo/linkedin.svg',
  'contact_phone_text' => '(123)-456-7898',
  'contact_phone_link' => '123456780',
  'contact_phone_des' => 'Call Us any time',
  'contact_phone_icon' =>  get_template_directory_uri().'/assets/images-demo/phone-portrait.svg',
  'contact_email_text' => 'info@gmail.com',
  'contact_email_des' => 'info@gmail.com',
  'contact_email_icon' =>  get_template_directory_uri().'/assets/images-demo/mail.svg',
  'contact_hours_icon' =>  get_template_directory_uri().'/assets/images-demo/time.svg',
  'contact_hours_text' => 'Monday to Friday',
  'contact_hours_des' => '9AM-10PM',
  'contact_address_line1' => 'Link Road Ri Sheab',
  'contact_address_line2' => 'Shona Danga',
  'contact_address_icon' =>  get_template_directory_uri().'/assets/images-demo/map-pin.svg',
);